#!/bin/sh
#
#  $Id: xctest,v 1.6 2001/09/19 08:38:01 kims Exp $
# 
#  xctest - shell script to test xclip
#  Copyright (c) 2001 Kim Saunders
#  Copyright (c) 2008 Diego 'Flameeyes' Pettenò
#
#  This file is part of xcbclip.
#
#  xcbclip is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  xcbclip is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with xcbclip.  If not, see <http://www.gnu.org/licenses/>.

delay=1 # seconds to wait before running xcbclip -o

# test to make sure ./xcbclip exists
if [ ! -f xcbclip ];
then
	echo "Error: xcbclip doesn't exist in the current directory."
	exit 1
fi

checker=""

for param in $@;
do
	case $param in
		--valgrind) checker="valgrind --num-callers=8";;
	esac
done

# test xcbclip on different amounts of data to bring out any errors
for lines in 2 16 128 1024 8192
do
	# temp file names (in and out)
	tempi=`tempfile`
	tempo=`tempfile`

	linec=0	# current line of file in while loop

	# append lines two at a time to input temp file
	while [ $linec -lt `expr $lines / 2` ]
	do
		echo -n -e "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890\n" >> $tempi
		echo -n -e "abcdefghijklmnopqrstuvwzyz!@#$%^&*()\n" >> $tempi
		linec=$(($linec+1))
	done

	# test piping the file to xcbclip, using all selections
	echo Piping a $lines line file to xcbclip
	for sel in primary secondary clipboard buffer
	do
		echo "  Using the $sel selection"
		cat $tempi | $checker ./xcbclip -sel $sel -i
		sleep $delay
		$checker ./xcbclip -sel $sel -o > $tempo
		diff $tempi $tempo
	done
	echo

	# test xcbclip reading the file
	echo Reading a $lines line file with xcbclip
	for sel in primary secondary clipboard buffer
	do
		echo "  Using the $sel selection"
		$checker ./xcbclip -sel $sel -i $tempi
		sleep $delay
		$checker ./xcbclip -sel $sel -o > $tempo
		diff $tempi $tempo
	done
	echo
	
	# test xcbclip filtering a file
	echo Filtering a $lines line file through xcbclip
	for sel in primary secondary clipboard buffer
	do
		echo "  Using the $sel selection"
		$checker ./xcbclip -sel $sel -f < $tempi > $tempo
		sleep $delay
		diff $tempi $tempo
	done
	echo

	# quietly remove temp files
	rm $tempi $tempo 2> /dev/null
done

# Kill any remain xcbclip processes
killall xcbclip
